version: 2

sources:
  - name: raw_data
    description: Raw taxi trip data from NYC TLC
    database: |
      {%- if target.type == 'bigquery' -%}
        {{ env_var('GCP_PROJECT_ID', 'zoomcamp-test-2') }}
      {%- else -%}
        taxi_rides_ny
      {%- endif -%}
    schema: |
      {%- if target.type == 'bigquery' -%}
        zoomcamp
      {%- else -%}
        prod
      {%- endif -%}
    tables:
      - name: green_tripdata
        description: Raw green taxi trip records
        columns:
          - name: vendorid
          - name: lpep_pickup_datetime
          - name: lpep_dropoff_datetime
          - name: pulocationid
          - name: dolocationid

      - name: yellow_tripdata
        description: Raw yellow taxi trip records
        columns:
          - name: vendorid
          - name: tpep_pickup_datetime
          - name: tpep_dropoff_datetime
          - name: pulocationid
          - name: dolocationid
      - name: fhv_tripdata
        description: Raw FHV 2019 trip records
        columns:
          - name: dispatching_base_num
          - name: pickup_datetime
          - name: dropoff_datetime
          - name: pulocationid
          - name: dolocationid
          - name: sr_flag
          - name: affiliated_base_number