version: 2

sources:
  - name: raw_data
    description: "raw data sources for NYC taxi rides"
    database: zoomcamp-test-2
    schema: zoomcamp
    tables:
      - name: yellow_tripdata
      - name: green_tripdata

